<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use App\Models\OrderHotels;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use App\Http\Controllers\MailController;
use App\Http\Controllers\Hotel\Amadeus\HeaderController;
use App\Models\HotelAddPaymentDetails;
use App\Models\PaymentHotels;


class PaymentController extends Controller
{
    public function create(Request $request)
	{
    //    dd($request->all());
        $order = new PaymentHotels;
        $order->order_amount= $request->orderAmount;
        $order->order_id=$request->orderId;
        $order->reference_id=$request->referenceId;
        $order->sign=$request->signature;
        $order->txMsg=$request->txMsg;
        $order->txStatus=$request->txStatus;
        $order->txtime=$request->txTime;
        $order->payment_mode=$request->paymentMode;
        $order->save();


        $datas = $request->all();
        $data =DB::table('paymentdatas')->where('id','like',$request->orderId)->get()->first();
        // dd($request->orderId);
        // dd($data);
        $payModel = new HotelAddPaymentDetails;
        $payModel->address = $data->address;
        $payModel->hotelname = $data->HotelName;
        $payModel->check = $data->checkin.' | '.$data->checkout;
        $payModel->adult =$data->adult;
        $payModel->name = $data->adultFirstName.$data->adultLastName;
        $payModel->phone = $data->phoneNumber;
        $payModel->email =$data->email;
        $payModel->amount = $request->orderAmount;
        $payModel->uniqueid = "MMTHOTEL".rand(1,1000);
        $payModel->payment_id = $request['orderId'];
        $payModel->booking_code = $request['orderId'];
        $payModel->save();
        

        $action = "PNRADD_17_1_1A";
        $header = json_decode($data->header);
        $xml = '';
        $xml .= '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:typ="http://xml.amadeus.com/2010/06/Types_v1" xmlns:iat="http://www.iata.org/IATA/2007/00/IATA2010.1" xmlns:app="http://xml.amadeus.com/2010/06/AppMdw_CommonTypes_v3" xmlns:link="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:ses="http://xml.amadeus.com/2010/06/Session_v3" xmlns:pnr="http://xml.amadeus.com/PNRADD_14_1_1A">';
        $xml .= HeaderController::headerInSeries($action, $header);
        $xml .= '<soapenv:Body>';
        $xml .= '<PNR_AddMultiElements xmlns="http://xml.amadeus.com/PNRADD_17_1_1A">';
        $xml .= '<pnrActions>';
        $xml .= '<optionCode>0</optionCode>';
        $xml .= '</pnrActions>';
        $xml .= '<travellerInfo>';
        $xml .= '<elementManagementPassenger>';
        $xml .= '<reference>';
        $xml .= '<qualifier>PR</qualifier>';
        $xml .= '<number>1</number>';
        $xml .= '</reference>';
        $xml .= '<segmentName>NM</segmentName>';
        $xml .= '</elementManagementPassenger>';
        $xml .= '<passengerData>';
        $xml .= '<travellerInformation>';
        $xml .= '<traveller>';
        $xml .= '<surname>'. $data->adultLastName.'</surname>';
        $xml .= '<quantity>1</quantity>';
        $xml .= '</traveller>';
        $xml .= '<passenger>';
        $xml .= '<firstName>'. $data->adultFirstName.'</firstName>';
        $xml .= '</passenger>';
        $xml .= '</travellerInformation>';
        $xml .= '</passengerData>';
        $xml .= '</travellerInfo>';
        $xml .= '<dataElementsMaster>';
        $xml .= '<marker1/>';
        $xml .= '<dataElementsIndiv>';
        $xml .= '<elementManagementData>';
        $xml .= '<segmentName>RM</segmentName>';
        $xml .= '</elementManagementData>';
        $xml .= '<miscellaneousRemark>';
        $xml .= '<remarks>';
        $xml .= '<type>RM</type>';
        $xml .= '<freetext>WAGNISTRIP PRIVATE LIMITED.</freetext>';
        $xml .= '</remarks>';
        $xml .= '</miscellaneousRemark>';
        $xml .= '</dataElementsIndiv>';
        $xml .= '<dataElementsIndiv>';
        $xml .= '<elementManagementData>';
        $xml .= '<reference>';
        $xml .= '<qualifier>OT</qualifier>';
        $xml .= '<number>3</number>';
        $xml .= '</reference>';
        $xml .= '<segmentName>RF</segmentName>';
        $xml .= '</elementManagementData>';
        $xml .= '<freetextData>';
        $xml .= '<freetextDetail>';
        $xml .= '<subjectQualifier>3</subjectQualifier>';
        $xml .= '<type>3</type>';
        $xml .= '</freetextDetail>';
        $xml .= '<longFreetext>' . $data->email . '</longFreetext>';
        $xml .= '</freetextData>';
        $xml .= '</dataElementsIndiv>';
        $xml .= '<dataElementsIndiv>';
        $xml .= '<elementManagementData>';
        $xml .= '<reference>';
        $xml .= '<qualifier>OT</qualifier>';
        $xml .= '<number>3</number>';
        $xml .= '</reference>';
        $xml .= '<segmentName>TK</segmentName>';
        $xml .= '</elementManagementData>';
        $xml .= '<ticketElement>';
        $xml .= '<ticket>';
        $xml .= '<indicator>TL</indicator>';
        $xml .= '<date>' . date("dmy") . '</date>';
        $xml .= '</ticket>';
        $xml .= '</ticketElement>';
        $xml .= '</dataElementsIndiv>';
        $xml .= '<dataElementsIndiv>';
        $xml .= '<elementManagementData>';
        $xml .= '<reference>';
        $xml .= '<qualifier>OT</qualifier>';
        $xml .= '<number>3</number>';
        $xml .= '</reference>';
        $xml .= '<segmentName>AP</segmentName>';
        $xml .= '</elementManagementData>';
        $xml .= '<freetextData>';
        $xml .= '<freetextDetail>';
        $xml .= '<subjectQualifier>3</subjectQualifier>';
        $xml .= '<type>3</type>';
        $xml .= '</freetextDetail>';
        $xml .= '<longFreetext>'. $data->phoneNumber .'</longFreetext>';
        $xml .= '</freetextData>';
        $xml .= '</dataElementsIndiv>';
        $xml .= '</dataElementsMaster>';
        $xml .= '</PNR_AddMultiElements>';
        $xml .= '</soapenv:Body>';
        $xml .= '</soapenv:Envelope>';
        // dd($xml);
        
        $result = HeaderController::xmlCallWithBodyAndHeader2($xml, "PNRADD_17_1_1A_0");
        $detail = $result['body'];
        $headerSell = json_encode($result['header']['awsseSession'], true);
        $headerSell = json_decode($headerSell);
        // dd($detail);
        $actionSell = "HBKRCQ_17_1_1A";
        $xmlsell = '';
        $xmlsell .= '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:typ="http://xml.amadeus.com/2010/06/Types_v1" xmlns:iat="http://www.iata.org/IATA/2007/00/IATA2010.1" xmlns:app="http://xml.amadeus.com/2010/06/AppMdw_CommonTypes_v3" xmlns:link="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:ses="http://xml.amadeus.com/2010/06/Session_v3" xmlns:hbk="http://xml.amadeus.com/HBKRCQ_13_2_1A">';
        $xmlsell .= HeaderController::headerInSeries($actionSell, $headerSell);
        $xmlsell .= '<soapenv:Body>';
        $xmlsell .= '<Hotel_Sell xmlns="http://xml.amadeus.com/HBKRCQ_17_1_1A">';
        $xmlsell .= '<roomStayData>';
        $xmlsell .= '<markerRoomStayData></markerRoomStayData>';
        $xmlsell .= '<globalBookingInfo>';
        $xmlsell .= '<markerGlobalBookingInfo></markerGlobalBookingInfo>';
        $xmlsell .= '<bookingSource>';
        $xmlsell .= '<originIdentification>';
        $xmlsell .= '<originatorId>14385420</originatorId>';
        $xmlsell .= '</originIdentification>';
        $xmlsell .= '</bookingSource>';
        $xmlsell .= '<representativeParties>';
        $xmlsell .= '<occupantList>';
        $xmlsell .= '<passengerReference>';
        $xmlsell .= '<type>BHO</type>';
        $xmlsell .= '<value>2</value>';
        $xmlsell .= '</passengerReference>';
        $xmlsell .= '</occupantList>';
        $xmlsell .= '</representativeParties>';
        $xmlsell .= '</globalBookingInfo>';
        $xmlsell .= '<roomList>';
        $xmlsell .= '<markerRoomstayQuery></markerRoomstayQuery>';
        $xmlsell .= '<roomRateDetails>';
        $xmlsell .= '<marker></marker>';
        $xmlsell .= '<hotelProductReference>';
        $xmlsell .= '<referenceDetails>';
        $postvalue = $data;
        // dd($postvalue);
        $xmlsell .= '<type>BC</type>';
        $xmlsell .= '<value>' . $data->booking_code . '</value>';
        $xmlsell .= '</referenceDetails>';
        $xmlsell .= '</hotelProductReference>';
        $xmlsell .= '<markerOfExtra></markerOfExtra>';
        $xmlsell .= '</roomRateDetails>';
        $xmlsell .= '<guaranteeOrDeposit>';
        $xmlsell .= '<paymentInfo>';
        $xmlsell .= '<paymentDetails>';
        $xmlsell .= '<formOfPaymentCode>1</formOfPaymentCode>';
        $xmlsell .= '<paymentType>1</paymentType>';
        $xmlsell .= '<serviceToPay>3</serviceToPay>';
        $xmlsell .= '</paymentDetails>';
        $xmlsell .= '</paymentInfo>';
        $xmlsell .= '<groupCreditCardInfo>';
        $xmlsell .= '<creditCardInfo>';
        $xmlsell .= '<ccInfo>';
        $xmlsell .= '<vendorCode>VI</vendorCode>';
        $xmlsell .= '<cardNumber>4263982640269299</cardNumber>';
        $xmlsell .= '<securityId>837</securityId>';
        $xmlsell .= '<expiryDate>0223</expiryDate>';
        $xmlsell .= '<ccHolderName>MAKETRUETRIP</ccHolderName>';
        $xmlsell .= '</ccInfo>';
        $xmlsell .= '</creditCardInfo>';
        $xmlsell .= '</groupCreditCardInfo>';
        $xmlsell .= '</guaranteeOrDeposit>';
        $xmlsell .= '</roomList>';
        $xmlsell .= '</roomStayData>';
        $xmlsell .= '</Hotel_Sell>';
        $xmlsell .= '</soapenv:Body>';
        $xmlsell .= '</soapenv:Envelope>';
        // dd($xmlsell);
        $resultSell = HeaderController::xmlCallWithBodyAndHeader2($xmlsell, $actionSell);
        $resultDetailBody = $resultSell['body'];
        $headerSell2 = json_encode($resultSell['header']['awsseSession'], true);
        $headerSell2 = json_decode($headerSell2);
        $actionRetrive = "PNRADD_17_1_1A";
        $xmlsellRetrive = '';
        $xmlsellRetrive .= '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:typ="http://xml.amadeus.com/2010/06/Types_v1" xmlns:iat="http://www.iata.org/IATA/2007/00/IATA2010.1" xmlns:app="http://xml.amadeus.com/2010/06/AppMdw_CommonTypes_v3" xmlns:link="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:ses="http://xml.amadeus.com/2010/06/Session_v3" xmlns:pnr="http://xml.amadeus.com/PNRADD_17_1_1A">';
        $xmlsellRetrive .= HeaderController::headerInSeries($actionRetrive, $headerSell2);
        $xmlsellRetrive .= '<soapenv:Body>';
        $xmlsellRetrive .= '<PNR_AddMultiElements xmlns="http://xml.amadeus.com/PNRADD_17_1_1A">';
        $xmlsellRetrive .= '<pnrActions>';
        $xmlsellRetrive .= '<optionCode>10</optionCode>';
        $xmlsellRetrive .= '</pnrActions>';
        $xmlsellRetrive .= '<dataElementsMaster>';
        $xmlsellRetrive .= '<marker1 />';
        $xmlsellRetrive .= '<dataElementsIndiv>';
        $xmlsellRetrive .= '<elementManagementData>';
        $xmlsellRetrive .= '<segmentName>RM</segmentName>';
        $xmlsellRetrive .= '</elementManagementData>';
        $xmlsellRetrive .= '<miscellaneousRemark>';
        $xmlsellRetrive .= '<remarks>';
        $xmlsellRetrive .= '<type>RM</type>';
        $xmlsellRetrive .= '<freetext>WagnisTrip Pvt. Ltd.</freetext>';
        $xmlsellRetrive .= '</remarks>';
        $xmlsellRetrive .= '</miscellaneousRemark>';
        $xmlsellRetrive .= '</dataElementsIndiv>';
        $xmlsellRetrive .= '<dataElementsIndiv>';
        $xmlsellRetrive .= '<elementManagementData>';
        $xmlsellRetrive .= '<segmentName>RF</segmentName>';
        $xmlsellRetrive .= '</elementManagementData>';
        $xmlsellRetrive .= '<freetextData>';
        $xmlsellRetrive .= '<freetextDetail>';
        $xmlsellRetrive .= '<subjectQualifier>3</subjectQualifier>';
        $xmlsellRetrive .= '<type>P22</type>';
        $xmlsellRetrive .= '</freetextDetail>';
        $xmlsellRetrive .= '<longFreetext>BOOKIN IS VIP</longFreetext>';
        $xmlsellRetrive .= '</freetextData>';
        $xmlsellRetrive .= '</dataElementsIndiv>';
        $xmlsellRetrive .= '</dataElementsMaster>';
        $xmlsellRetrive .= '</PNR_AddMultiElements>';
        $xmlsellRetrive .= '</soapenv:Body>';
        $xmlsellRetrive .= '</soapenv:Envelope>';
        // dd($xmlsellRetrive);
        $resultSellRetrive = HeaderController::xmlCallWithBodyAndHeader2($xmlsellRetrive, "PNRADD_17_1_1A");
        $resultSellRetriveBody = $resultSellRetrive['body'];
        // dd($resultSellRetriveBody);
        // uddeshya code error hendiling 
        // dd($resultSellRetriveBody);
        if(!isset($resultSellRetriveBody['PNR_Reply']['pnrHeader']['reservationInfo']['reservation']['controlNumber'])){
            $error = '';
            if(isset($resultSellRetriveBody['PNR_Reply']['generalErrorInfo']['errorWarningDescription']['freeText'])){
                $arrary = $resultSellRetriveBody['PNR_Reply']['generalErrorInfo']['errorWarningDescription']['freeText'];
                // dd($resultSellRetriveBody);
                $arrLength = count($arrary);
                for($i = 0; $i < $arrLength; $i++) {
                    $error.= $arrary[$i];
                }
            }
            return redirect()->route('error')->with('msg', 'Undefined index: controlNumber, and '. $error);
        }
        // end uddeshya code 
        $controlNumber = $resultSellRetriveBody['PNR_Reply']['pnrHeader']['reservationInfo']['reservation']['controlNumber'];
        $headerSell3 = json_encode($resultSellRetrive['header']['awsseSession'], true);
        $headerSell3 = json_decode($headerSell3);
        // dd($headerSell3);
        $actionRetriveRepeat = "PNRRET_17_1_1A";
        $xmlsellRetriveRepeat = '';
        $xmlsellRetriveRepeat .= '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:sec="http://xml.amadeus.com/2010/06/Security_v1" xmlns:typ="http://xml.amadeus.com/2010/06/Types_v1" xmlns:iat="http://www.iata.org/IATA/2007/00/IATA2010.1" xmlns:app="http://xml.amadeus.com/2010/06/AppMdw_CommonTypes_v3" xmlns:link="http://wsdl.amadeus.com/2010/06/ws/Link_v1" xmlns:ses="http://xml.amadeus.com/2010/06/Session_v3" xmlns:pnr="http://xml.amadeus.com/PNRADD_17_1_1A">';
        $xmlsellRetriveRepeat .= HeaderController::headerInSeries($actionRetriveRepeat, $headerSell3);
        $xmlsellRetriveRepeat .= '<soapenv:Body>';
        $xmlsellRetriveRepeat .= '<PNR_Retrieve xmlns="http://xml.amadeus.com/PNRRET_17_1_1A">';
        $xmlsellRetriveRepeat .= '<retrievalFacts>';
        $xmlsellRetriveRepeat .= '<retrieve>';
        $xmlsellRetriveRepeat .= '<type>2</type>';
        $xmlsellRetriveRepeat .= '</retrieve>';
        $xmlsellRetriveRepeat .= '<reservationOrProfileIdentifier>';
        $xmlsellRetriveRepeat .= '<reservation>';
        $xmlsellRetriveRepeat .= '<controlNumber>'.$controlNumber.'</controlNumber>';
        $xmlsellRetriveRepeat .= '</reservation>';
        $xmlsellRetriveRepeat .= '</reservationOrProfileIdentifier>';
        $xmlsellRetriveRepeat .= '</retrievalFacts>';
        $xmlsellRetriveRepeat .= '</PNR_Retrieve>';
        $xmlsellRetriveRepeat .= '</soapenv:Body>';
        $xmlsellRetriveRepeat .= '</soapenv:Envelope>';
        $resultsellRetriveRepeat = HeaderController::xmlCallWithBodyAndHeader2($xmlsellRetriveRepeat, $actionRetriveRepeat);
        // dd($resultsellRetriveRepeat['body']['soapFault']);
        // dd($resultsellRetriveRepeat['body'] ,$resultsellRetriveRepeat['body']['soapFault']);
        // dd($resultsellRetriveRepeat);
        $maildata = [
            'resultsellRetriveRepeat'=> $resultsellRetriveRepeat,
            'postvalue'=>$postvalue ,
            'data'=> $data
        ];
        MailController::bassendToCus($maildata);
        // dd($resultsellRetriveRepeat , $postvalue , $data);
        // MailController::bassendToCus($maildata);
        
        return view('hotel-pages.ticket', compact('resultsellRetriveRepeat','postvalue' , 'data'));
    }
}
